### ISSUE TITLE
Hello. New TPAMI paper for long-tailed learning

### ISSUE THREAD

**Issue by Andy-Du20** [Stomach-ache/awesome-long-tail-learning#10]
Hello! We want to introduce our new paper,  "Probabilistic Contrastive Learning for Long-Tailed Visual Recognition," published in TPAMI 2024. This work applies contrastive learning to tackle the challenges of long-tailed visual recognition.

Paper: https://arxiv.org/pdf/2403.06726
Code: https://github.com/LeapLabTHU/ProCo

We hope our work is a valuable addition to the community and look forward to your feedback.

**Comment by Stomach-ache** [comment]
The paper has been added to the list. Thanks for your contribution!
