### ISSUE TITLE
Hi, New Long Tail Papers [ICML2024, NeurIPS2023]

### ISSUE THREAD

**Issue by wang22ti** [Stomach-ache/awesome-long-tail-learning#9]
Hi,

Thank you for maintaining the comprehensive list of papers on long-tailed learning.

We would like to introduce two recent papers to be considered for inclusion:

1. **Harnessing Hierarchical Label Distribution Variations in Test Agnostic Long-tail Recognition (ICML 2024)** [[pdf]](https://arxiv.org/abs/2405.07780) [[code]](https://github.com/scongl/DirMixE)
   
   This paper presents DirMixE, an innovative Mixture-of-Expert framework designed for test-agnostic long-tail recognition. DirMixE utilizes Dirichlet meta-distributions to capture both local and global variations in label distributions, enhancing the framework's generalization and performance stability.

2. **A Unified Generalization Analysis of Re-Weighting and Logit-Adjustment for Imbalanced Learning (NeurIPS 2023)** [[pdf]](https://arxiv.org/abs/2310.04752) [[code]](https://github.com/wang22ti/DDC)

   This paper introduces a novel data-dependent contraction technique to provide a detailed generalization bound for imbalanced learning. It offers a unified explanation for re-weighting and logit-adjustment methods and proposes a principled learning algorithm validated by empirical results on benchmark datasets.

We would greatly appreciate it if you could include these papers in your list.

Thank you very much!

**Comment by Stomach-ache** [comment]
Thanks for your contribution! The papers you provided have been successfully added to the list.

**Comment by wang22ti** [comment]
Thanks again for maintaining this list of papers on long-tailed learning!
